name: notices

on:
  issues:
    types: [opened]
  pull_request:
    branches: 
      - master
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: letstestthatpipe/first-interaction@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'this is a legal footer'
        pr-message: 'this is a pr legal footer'
    
     
  
